---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: my-webapp-foo
  namespace: argocd
  finalizers: 
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source: 
    repoURL: https://github.com/ajaypani/infra.git
    targetRevision: HEAD
    path: environments/staging/my-webapp
  destination: 
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true


